### ISSUE TITLE
Extensão para o navegador.

### ISSUE THREAD

**Issue by fariasmateuss** [wandersonsousa/deletar-mensagens-facebook#1]
Atribua seu script a uma extensão para o navegador por meio, por exemplo, do content_scripts criando manifest.json. Assim, torna mais fácil e dinâmica a utilização do seu script.
 
Para criar um content_scripts, basta adicionar no manifest.json as seguintes linhas:

```js
"content_scripts": [{
    "js": [ "script.js"],
    "matches": ["*://*/*"]
}],

```

Para rodar o content_script, é necessária uma permissão de leitura e escrita de abas que deve ser informada no próprio manifest.json:

```js
"permissions": [
    "tabs"     
]
```

**Comment by wandersonsousa** [comment]
Boa sacada a de transformar em uma extensão,  vou atualizar quando puder, sim. Obrigado :)
